//  =============== BEGIN ASSESSMENT HEADER ================
/// @file assn8/main.cpp
/// @brief assn8 for CS 12v Winter 2014
///
/// @author Rica Feng [rfeng001@ucr.edu]
/// @date March 12, 2014
///
/// @par Enrollment Notes 
///     Lecture Section: NA
/// @par
///     Lab Section: NA
/// @par
///     TA: Juan
///
/// @par Plagiarism Section
/// I hereby certify that the code in this file
/// is ENTIRELY my own original work.
//  =============== END ASSESSMENT HEADER ==================

COMPILE = g++
FLAG = -W -Wall -Werror -pedantic -ansi
OBJS = BBoard

User.o: User.cpp User.h
	g++ -W -Wall -Werror -pedantic -ansi User.cpp
	
Message.o: Message.cpp Message.h
	g++ -W -Wall -Werror -pedantic -ansi User.cpp
	
Topic.o: Topic.cpp Topic.h Message.h
	g++ -W -Wall -Werror -pedantic -ansi User.cpp
	
Reply.o: Reply.cpp Reply.h Message.h
	g++ -W -Wall -Werror -pedantic -ansi User.cpp